[project]
name = "workstreams"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "requests>=2.32.5",
    "openai>=1.58.1",
    "jira>=3.10.5",
]
